runtime: python312
entrypoint: gunicorn -b :$PORT main:app
service: default
env: flexible
manual_scaling:
  instances: 1

handlers:
  - url: /static
    static_dir: static

  - url: /.*
    script: auto