runtime: python312
service: default
env: flexible
entrypoint: gunicorn -b :$PORT main:app

# Manual scaling configuration
manual_scaling:
  instances: 1

# Resource allocation (adjust based on your needs)
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
    secure: always

  - url: /.*
    script: auto
    secure: always

# Environment variables if needed
env_variables:
  PYTHON_ENV: "production"